name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Build (export)
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build

      # Guardrails to ensure build succeeded
      - name: Verify build output
        run: |
          echo "Checking build output..."
          ls -la
          echo "--- ./out directory ---"
          ls -la ./out
          echo "--- Checking for index.html ---"
          if [ ! -f "./out/index.html" ]; then
            echo "ERROR: index.html not found in ./out directory!"
            exit 1
          else
            echo "✅ index.html found in ./out directory"
            ls -la ./out/index.html
          fi

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          force_orphan: true
